version: "3.8"

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    restart: unless-stopped

  order-service:
    build:
      context: ./order-service
    ports:
      - "3002:3002"
    env_file:
      - ./order-service/.env
    restart: unless-stopped

  product-service:
    build:
      context: ./product-service
    ports:
      - "8000:8000"
    env_file:
      - ./product-service/.env
    restart: unless-stopped
